### ISSUE TITLE
Strange trouble when forking...

### ISSUE THREAD

**Issue by serjevski** [bitwiseshiftleft/factorio-router#1]
HI, I try to for your project for Russian translation, but when i clone repo to Windows computer it can't create folder named 'aux' - it a special reserved name. Could You rename this folder to anything else? :))

**Comment by serjevski** [comment]
here is explanation.. https://confluence.atlassian.com/bamkb/invalid-argument-error-when-trying-to-checkout-repository-inside-windows-agent-1071824236.html

**Comment by bitwiseshiftleft** [comment]
Ah OK, changed to _aux.

**Comment by serjevski** [comment]
Thanks! I'll try tomorrow :)
